# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = battleshipMain.o Classes.o classesAI.o
LINKOBJ  = battleshipMain.o Classes.o classesAI.o
LIBS     = -L"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/lib" -L"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg -g3
INCS     = -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/andrea/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = BattagliaNavale.exe
CXXFLAGS = $(CXXINCS) -pg -g3
CFLAGS   = $(INCS) -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

battleshipMain.o: battleshipMain.cpp
	$(CPP) -c battleshipMain.cpp -o battleshipMain.o $(CXXFLAGS)

Classes.o: Classes.cpp
	$(CPP) -c Classes.cpp -o Classes.o $(CXXFLAGS)

classesAI.o: classesAI.cpp
	$(CPP) -c classesAI.cpp -o classesAI.o $(CXXFLAGS)
